name: retrier
description: A starting point for Dart libraries or applications.
version: 0.0.1
author: Erlantz Oniga <erlantz8@gmail.com>
homepage: http://www.erlantzoniga.com

environment:
  sdk: '>=1.0.0 <2.0.0'

#dependencies:
#  lib_name: any

dev_dependencies:
  test: ^0.12.0
